"""create creative concept and script foundation

Revision ID: 64197719c817
Revises: d0e1f2a3b4c5
Create Date: 2026-07-16 15:00:24.329894
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "64197719c817"
down_revision: str | None = "d0e1f2a3b4c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creative_concept_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("brief_content_digest", sa.String(length=64), nullable=False),
        sa.Column("instruction_template_id", sa.String(length=100), nullable=False),
        sa.Column("instruction_template_version", sa.String(length=30), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("candidate_count", sa.Integer(), server_default="3", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_category", sa.String(length=30), nullable=True),
        sa.Column("created_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("brief_content_digest ~ '^[0-9a-f]{64}$'", name="ck_concept_run_digest"),
        sa.CheckConstraint(
            "failure_category IN ('refusal', 'timeout', 'provider_error', "
            "'malformed_output', 'schema_invalid') OR failure_category IS NULL",
            name="ck_concept_run_failure",
        ),
        sa.CheckConstraint("status IN ('completed', 'failed')", name="ck_concept_run_status"),
        sa.CheckConstraint("candidate_count = 3", name="ck_concept_run_candidate_count"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "brief_id", "brief_version_id"],
            [
                "brief_versions.organization_id",
                "brief_versions.workspace_id",
                "brief_versions.project_id",
                "brief_versions.brief_id",
                "brief_versions.id",
            ],
            name="fk_concept_runs_brief_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "project_id", "id", name="uq_concept_runs_tenant_id"
        ),
    )
    op.create_table(
        "creative_concept_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_index", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_digest ~ '^[0-9a-f]{64}$'", name="ck_concept_candidate_digest"),
        sa.CheckConstraint("candidate_index BETWEEN 1 AND 3", name="ck_concept_candidate_index"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "concept_run_id"],
            [
                "creative_concept_runs.organization_id",
                "creative_concept_runs.workspace_id",
                "creative_concept_runs.project_id",
                "creative_concept_runs.id",
            ],
            name="fk_concept_candidates_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concept_run_id", "candidate_index", name="uq_concept_candidates_index"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_concept_candidates_tenant_plain_id",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "concept_run_id",
            "id",
            name="uq_concept_candidates_tenant_id",
        ),
    )
    op.create_table(
        "creative_concept_selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("selected_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name="ck_concept_selection_version"),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "concept_run_id",
                "concept_candidate_id",
            ],
            [
                "creative_concept_candidates.organization_id",
                "creative_concept_candidates.workspace_id",
                "creative_concept_candidates.project_id",
                "creative_concept_candidates.concept_run_id",
                "creative_concept_candidates.id",
            ],
            name="fk_concept_selection_candidate",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_run_id", name="uq_concept_selection_run"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "concept_run_id",
            "concept_candidate_id",
            "id",
            name="uq_concept_selection_lineage",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_concept_selection_tenant_id",
        ),
    )
    op.create_table(
        "script_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("brief_content_digest", sa.String(length=64), nullable=False),
        sa.Column("concept_content_digest", sa.String(length=64), nullable=False),
        sa.Column("instruction_template_id", sa.String(length=100), nullable=False),
        sa.Column("instruction_template_version", sa.String(length=30), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_category", sa.String(length=30), nullable=True),
        sa.Column("created_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "brief_content_digest ~ '^[0-9a-f]{64}$' AND concept_content_digest ~ '^[0-9a-f]{64}$'",
            name="ck_script_run_digests",
        ),
        sa.CheckConstraint("status IN ('completed', 'failed')", name="ck_script_run_status"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "brief_id", "brief_version_id"],
            [
                "brief_versions.organization_id",
                "brief_versions.workspace_id",
                "brief_versions.project_id",
                "brief_versions.brief_id",
                "brief_versions.id",
            ],
            name="fk_script_runs_brief_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "concept_run_id",
                "concept_candidate_id",
            ],
            [
                "creative_concept_candidates.organization_id",
                "creative_concept_candidates.workspace_id",
                "creative_concept_candidates.project_id",
                "creative_concept_candidates.concept_run_id",
                "creative_concept_candidates.id",
            ],
            name="fk_script_runs_candidate",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
            ],
            [
                "creative_concept_selections.organization_id",
                "creative_concept_selections.workspace_id",
                "creative_concept_selections.project_id",
                "creative_concept_selections.concept_run_id",
                "creative_concept_selections.concept_candidate_id",
                "creative_concept_selections.id",
            ],
            name="fk_script_runs_selection",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "project_id", "id", name="uq_script_runs_tenant_id"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            "brief_id",
            "brief_version_id",
            "concept_run_id",
            "concept_candidate_id",
            "concept_selection_id",
            name="uq_script_runs_lineage",
        ),
    )
    op.create_table(
        "script_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("script_run_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_digest ~ '^[0-9a-f]{64}$'", name="ck_script_version_digest"),
        sa.CheckConstraint("version_number = 1", name="ck_script_version_number"),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "script_run_id",
                "brief_id",
                "brief_version_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
            ],
            [
                "script_runs.organization_id",
                "script_runs.workspace_id",
                "script_runs.project_id",
                "script_runs.id",
                "script_runs.brief_id",
                "script_runs.brief_version_id",
                "script_runs.concept_run_id",
                "script_runs.concept_candidate_id",
                "script_runs.concept_selection_id",
            ],
            name="fk_script_versions_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_script_versions_tenant_id",
        ),
        sa.UniqueConstraint("script_run_id", "version_number", name="uq_script_versions_number"),
    )
    op.create_table(
        "creative_generation_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("outcome_concept_run_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_selection_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_script_run_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_script_version_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(status='reserved' AND completed_at IS NULL AND outcome_concept_run_id IS NULL "
            "AND outcome_candidate_id IS NULL AND outcome_selection_id IS NULL "
            "AND outcome_script_run_id IS NULL AND outcome_script_version_id IS NULL) OR "
            "(status='accepted' AND completed_at IS NOT NULL AND ((operation="
            "'generate_creative_concepts' AND outcome_concept_run_id IS NOT NULL) OR "
            "(operation='select_creative_concept' AND outcome_selection_id IS NOT NULL "
            "AND outcome_candidate_id IS NOT NULL) OR (operation='generate_script' "
            "AND outcome_script_run_id IS NOT NULL AND outcome_script_version_id IS NOT NULL)))",
            name="ck_creative_operation_outcome",
        ),
        sa.CheckConstraint(
            "operation IN ('generate_creative_concepts', 'select_creative_concept', "
            "'generate_script')",
            name="ck_creative_operation_type",
        ),
        sa.CheckConstraint(
            "request_digest ~ '^[0-9a-f]{64}$'", name="ck_creative_operation_digest"
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'accepted')", name="ck_creative_operation_status"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name="fk_creative_operation_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_candidate_id"],
            [
                "creative_concept_candidates.organization_id",
                "creative_concept_candidates.workspace_id",
                "creative_concept_candidates.project_id",
                "creative_concept_candidates.id",
            ],
            name="fk_creative_operation_candidate",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_concept_run_id"],
            [
                "creative_concept_runs.organization_id",
                "creative_concept_runs.workspace_id",
                "creative_concept_runs.project_id",
                "creative_concept_runs.id",
            ],
            name="fk_creative_operation_concept_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_script_run_id"],
            [
                "script_runs.organization_id",
                "script_runs.workspace_id",
                "script_runs.project_id",
                "script_runs.id",
            ],
            name="fk_creative_operation_script_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_script_version_id"],
            [
                "script_versions.organization_id",
                "script_versions.workspace_id",
                "script_versions.project_id",
                "script_versions.id",
            ],
            name="fk_creative_operation_script_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_selection_id"],
            [
                "creative_concept_selections.organization_id",
                "creative_concept_selections.workspace_id",
                "creative_concept_selections.project_id",
                "creative_concept_selections.id",
            ],
            name="fk_creative_operation_selection",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "operation",
            "idempotency_key",
            name="uq_creative_generation_operation_key",
        ),
    )
    op.drop_constraint("ck_audit_action", "audit_events", type_="check")
    op.create_check_constraint(
        "ck_audit_action",
        "audit_events",
        "action IN ('organization.created', 'workspace.created', 'membership.created', "
        "'project.created', 'project.updated', 'project.activated', 'project.archived', "
        "'brief.created', 'brief.version_created', 'brief.submitted_for_review', "
        "'brief.approved', 'brief.archived', 'brief.issue_created', 'brief.issue_resolved', "
        "'brief.issue_dismissed', 'brief.ingestion_accepted', 'brief_ingestion.source_attached', "
        "'source_asset.created', 'source_asset.version_created', 'source_asset.archived', "
        "'source_object.uploaded', 'document_extraction.completed', 'brief_extraction.completed', "
        "'brief_candidate.accepted', 'brief_candidate.rejected', 'creative_concept.generated', "
        "'creative_concept.selected', 'script.generated')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("creative_generation_operations")
    op.drop_table("script_versions")
    op.drop_table("script_runs")
    op.drop_table("creative_concept_selections")
    op.drop_table("creative_concept_candidates")
    op.drop_table("creative_concept_runs")
    op.drop_constraint("ck_audit_action", "audit_events", type_="check")
    op.create_check_constraint(
        "ck_audit_action",
        "audit_events",
        "action IN ('organization.created', 'workspace.created', 'membership.created', "
        "'project.created', 'project.updated', 'project.activated', 'project.archived', "
        "'brief.created', 'brief.version_created', 'brief.submitted_for_review', "
        "'brief.approved', 'brief.archived', 'brief.issue_created', 'brief.issue_resolved', "
        "'brief.issue_dismissed', 'brief.ingestion_accepted', 'brief_ingestion.source_attached', "
        "'source_asset.created', 'source_asset.version_created', 'source_asset.archived', "
        "'source_object.uploaded', 'document_extraction.completed', 'brief_extraction.completed', "
        "'brief_candidate.accepted', 'brief_candidate.rejected')",
    )
    # ### end Alembic commands ###
