"""create storyboard and shot plan foundation

Revision ID: 9031dcffc3ea
Revises: 64197719c817
Create Date: 2026-07-16 15:57:12.637226
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9031dcffc3ea"
down_revision: str | None = "64197719c817"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_AUDIT = (
    "action IN ('organization.created', 'workspace.created', 'membership.created', "
    "'project.created', 'project.updated', 'project.activated', 'project.archived', "
    "'brief.created', 'brief.version_created', 'brief.submitted_for_review', "
    "'brief.approved', 'brief.archived', 'brief.issue_created', 'brief.issue_resolved', "
    "'brief.issue_dismissed', 'brief.ingestion_accepted', 'brief_ingestion.source_attached', "
    "'source_asset.created', 'source_asset.version_created', 'source_asset.archived', "
    "'source_object.uploaded', 'document_extraction.completed', 'brief_extraction.completed', "
    "'brief_candidate.accepted', 'brief_candidate.rejected', 'creative_concept.generated', "
    "'creative_concept.selected', 'script.generated')"
)
_NEW_AUDIT = _OLD_AUDIT[:-1] + ", 'storyboard.generated', 'shot_plan.generated')"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_audit_action", "audit_events", type_="check")
    op.create_check_constraint("ck_audit_action", "audit_events", _NEW_AUDIT)
    op.create_unique_constraint(
        "uq_script_versions_lineage",
        "script_versions",
        [
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            "script_run_id",
            "brief_id",
            "brief_version_id",
            "concept_run_id",
            "concept_candidate_id",
            "concept_selection_id",
        ],
    )
    op.create_table(
        "storyboard_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("script_run_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("script_content_digest", sa.String(length=64), nullable=False),
        sa.Column("instruction_template_id", sa.String(length=100), nullable=False),
        sa.Column("instruction_template_version", sa.String(length=30), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_category", sa.String(length=30), nullable=True),
        sa.Column("created_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "script_content_digest ~ '^[0-9a-f]{64}$'", name="ck_storyboard_run_digest"
        ),
        sa.CheckConstraint(
            "failure_category IN ('refusal', 'timeout', 'provider_error', "
            "'malformed_output', 'schema_invalid', 'semantic_invalid') OR failure_category IS NULL",
            name="ck_storyboard_run_failure",
        ),
        sa.CheckConstraint("status IN ('completed', 'failed')", name="ck_storyboard_run_status"),
        sa.CheckConstraint("version >= 1", name="ck_storyboard_run_version"),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "script_version_id",
                "script_run_id",
                "brief_id",
                "brief_version_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
            ],
            [
                "script_versions.organization_id",
                "script_versions.workspace_id",
                "script_versions.project_id",
                "script_versions.id",
                "script_versions.script_run_id",
                "script_versions.brief_id",
                "script_versions.brief_version_id",
                "script_versions.concept_run_id",
                "script_versions.concept_candidate_id",
                "script_versions.concept_selection_id",
            ],
            name="fk_storyboard_runs_script_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            "brief_id",
            "brief_version_id",
            "concept_run_id",
            "concept_candidate_id",
            "concept_selection_id",
            "script_run_id",
            "script_version_id",
            name="uq_storyboard_runs_lineage",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_storyboard_runs_tenant_id",
        ),
    )
    op.create_table(
        "storyboard_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_run_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("script_run_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("total_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("scene_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_digest ~ '^[0-9a-f]{64}$'", name="ck_storyboard_version_digest"
        ),
        sa.CheckConstraint(
            "version_number = 1 AND total_duration_seconds > 0 AND scene_count BETWEEN 1 AND 60",
            name="ck_storyboard_version_bounds",
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "storyboard_run_id",
                "brief_id",
                "brief_version_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
                "script_run_id",
                "script_version_id",
            ],
            [
                "storyboard_runs.organization_id",
                "storyboard_runs.workspace_id",
                "storyboard_runs.project_id",
                "storyboard_runs.id",
                "storyboard_runs.brief_id",
                "storyboard_runs.brief_version_id",
                "storyboard_runs.concept_run_id",
                "storyboard_runs.concept_candidate_id",
                "storyboard_runs.concept_selection_id",
                "storyboard_runs.script_run_id",
                "storyboard_runs.script_version_id",
            ],
            name="fk_storyboard_versions_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            "storyboard_run_id",
            "brief_id",
            "brief_version_id",
            "concept_run_id",
            "concept_candidate_id",
            "concept_selection_id",
            "script_run_id",
            "script_version_id",
            name="uq_storyboard_versions_lineage",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_storyboard_versions_tenant_id",
        ),
        sa.UniqueConstraint(
            "storyboard_run_id", "version_number", name="uq_storyboard_versions_number"
        ),
    )
    op.create_table(
        "shot_plan_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_run_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_version_id", sa.Uuid(), nullable=False),
        sa.Column("script_run_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_content_digest", sa.String(length=64), nullable=False),
        sa.Column("instruction_template_id", sa.String(length=100), nullable=False),
        sa.Column("instruction_template_version", sa.String(length=30), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_category", sa.String(length=30), nullable=True),
        sa.Column("created_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('completed', 'failed')", name="ck_shot_plan_run_status"),
        sa.CheckConstraint(
            "failure_category IN ('refusal', 'timeout', 'provider_error', "
            "'malformed_output', 'schema_invalid', 'semantic_invalid') OR failure_category IS NULL",
            name="ck_shot_plan_run_failure",
        ),
        sa.CheckConstraint(
            "storyboard_content_digest ~ '^[0-9a-f]{64}$'", name="ck_shot_plan_run_digest"
        ),
        sa.CheckConstraint("version >= 1", name="ck_shot_plan_run_version"),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "storyboard_version_id",
                "storyboard_run_id",
                "brief_id",
                "brief_version_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
                "script_run_id",
                "script_version_id",
            ],
            [
                "storyboard_versions.organization_id",
                "storyboard_versions.workspace_id",
                "storyboard_versions.project_id",
                "storyboard_versions.id",
                "storyboard_versions.storyboard_run_id",
                "storyboard_versions.brief_id",
                "storyboard_versions.brief_version_id",
                "storyboard_versions.concept_run_id",
                "storyboard_versions.concept_candidate_id",
                "storyboard_versions.concept_selection_id",
                "storyboard_versions.script_run_id",
                "storyboard_versions.script_version_id",
            ],
            name="fk_shot_plan_runs_storyboard",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            "storyboard_run_id",
            "storyboard_version_id",
            "brief_id",
            "brief_version_id",
            "concept_run_id",
            "concept_candidate_id",
            "concept_selection_id",
            "script_run_id",
            "script_version_id",
            name="uq_shot_plan_runs_lineage",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_shot_plan_runs_tenant_id",
        ),
    )
    op.create_table(
        "shot_plan_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("shot_plan_run_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_run_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_version_id", sa.Uuid(), nullable=False),
        sa.Column("script_run_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("brief_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_run_id", sa.Uuid(), nullable=False),
        sa.Column("concept_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("concept_selection_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("total_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("scene_count", sa.Integer(), nullable=False),
        sa.Column("shot_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_digest ~ '^[0-9a-f]{64}$'", name="ck_shot_plan_version_digest"),
        sa.CheckConstraint(
            "version_number = 1 AND total_duration_seconds > 0 AND scene_count BETWEEN 1 AND 60 "
            "AND shot_count BETWEEN 1 AND 180",
            name="ck_shot_plan_version_bounds",
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "workspace_id",
                "project_id",
                "shot_plan_run_id",
                "storyboard_run_id",
                "storyboard_version_id",
                "brief_id",
                "brief_version_id",
                "concept_run_id",
                "concept_candidate_id",
                "concept_selection_id",
                "script_run_id",
                "script_version_id",
            ],
            [
                "shot_plan_runs.organization_id",
                "shot_plan_runs.workspace_id",
                "shot_plan_runs.project_id",
                "shot_plan_runs.id",
                "shot_plan_runs.storyboard_run_id",
                "shot_plan_runs.storyboard_version_id",
                "shot_plan_runs.brief_id",
                "shot_plan_runs.brief_version_id",
                "shot_plan_runs.concept_run_id",
                "shot_plan_runs.concept_candidate_id",
                "shot_plan_runs.concept_selection_id",
                "shot_plan_runs.script_run_id",
                "shot_plan_runs.script_version_id",
            ],
            name="fk_shot_plan_versions_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "id",
            name="uq_shot_plan_versions_tenant_id",
        ),
        sa.UniqueConstraint(
            "shot_plan_run_id", "version_number", name="uq_shot_plan_versions_number"
        ),
    )
    op.create_table(
        "visual_planning_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("outcome_storyboard_run_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_storyboard_version_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_shot_plan_run_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_shot_plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_by_actor_subject", sa.String(length=200), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "operation IN ('generate_storyboard', 'generate_shot_plan')",
            name="ck_visual_operation_type",
        ),
        sa.CheckConstraint("status IN ('reserved', 'accepted')", name="ck_visual_operation_status"),
        sa.CheckConstraint("request_digest ~ '^[0-9a-f]{64}$'", name="ck_visual_operation_digest"),
        sa.CheckConstraint("version >= 1", name="ck_visual_operation_version"),
        sa.CheckConstraint(
            "(status='reserved' AND completed_at IS NULL AND outcome_storyboard_run_id IS NULL "
            "AND outcome_storyboard_version_id IS NULL AND outcome_shot_plan_run_id IS NULL "
            "AND outcome_shot_plan_version_id IS NULL) OR (status='accepted' "
            "AND completed_at IS NOT NULL "
            "AND ((operation='generate_storyboard' AND outcome_storyboard_run_id IS NOT NULL "
            "AND outcome_storyboard_version_id IS NOT NULL AND outcome_shot_plan_run_id IS NULL "
            "AND outcome_shot_plan_version_id IS NULL) OR (operation='generate_shot_plan' "
            "AND outcome_storyboard_run_id IS NULL AND outcome_storyboard_version_id IS NULL "
            "AND outcome_shot_plan_run_id IS NOT NULL "
            "AND outcome_shot_plan_version_id IS NOT NULL)))",
            name="ck_visual_operation_outcome",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id"],
            ["projects.organization_id", "projects.workspace_id", "projects.id"],
            name="fk_visual_operation_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_storyboard_run_id"],
            [
                "storyboard_runs.organization_id",
                "storyboard_runs.workspace_id",
                "storyboard_runs.project_id",
                "storyboard_runs.id",
            ],
            name="fk_visual_operation_storyboard_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_storyboard_version_id"],
            [
                "storyboard_versions.organization_id",
                "storyboard_versions.workspace_id",
                "storyboard_versions.project_id",
                "storyboard_versions.id",
            ],
            name="fk_visual_operation_storyboard_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_shot_plan_run_id"],
            [
                "shot_plan_runs.organization_id",
                "shot_plan_runs.workspace_id",
                "shot_plan_runs.project_id",
                "shot_plan_runs.id",
            ],
            name="fk_visual_operation_shot_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "project_id", "outcome_shot_plan_version_id"],
            [
                "shot_plan_versions.organization_id",
                "shot_plan_versions.workspace_id",
                "shot_plan_versions.project_id",
                "shot_plan_versions.id",
            ],
            name="fk_visual_operation_shot_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "project_id",
            "operation",
            "idempotency_key",
            name="uq_visual_planning_operation_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visual_planning_operations")
    op.drop_table("shot_plan_versions")
    op.drop_table("shot_plan_runs")
    op.drop_table("storyboard_versions")
    op.drop_table("storyboard_runs")
    op.drop_constraint("ck_audit_action", "audit_events", type_="check")
    op.create_check_constraint("ck_audit_action", "audit_events", _OLD_AUDIT)
    op.execute("ALTER TABLE script_versions DROP CONSTRAINT IF EXISTS uq_script_versions_lineage")
    # ### end Alembic commands ###
